### ISSUE TITLE
pdf失效问题

### ISSUE THREAD

**Issue by viys** [Akagi201/lw_oopc#8]
pdf失效了😭

**Comment by Celefor** [comment]
链接: https://pan.baidu.com/s/1WD0PEBsKNImqWHmwdq7qzA?pwd=bu7w 提取码: bu7w

**Comment by viys** [comment]
感谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Akagi201/lw_oopc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月12日(星期四) 上午8:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Akagi201/lw_oopc] pdf失效问题 (Issue #8)





 
链接: https://pan.baidu.com/s/1WD0PEBsKNImqWHmwdq7qzA?pwd=bu7w 提取码: bu7w

**Comment by Akagi201** [comment]
6, github 限流了, 这东西太占用流量了
